layout: sidebar
style: light
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-feed
permalink: '/:title/'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
social_media:
  x: filiptronicek
  linkedin: filiptronicek
title: Filip's Blog
author: filiptronicek
repository: "filiptronicek/blog"