layout: sidebar
style: light
plugins:
  - jekyll-octicons
  - jemoji
  - jekyll-feed
permalink: '/:title/'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
social_media:
  x: filiptronicek
  linkedin: filiptronicek
user:
  name: "Filip Troníček"
  login: filiptronicek
title: Filip's Blog
author: filiptronicek
repository: "filiptronicek/blog"
picture:
  suppress_warnings: true
