name: Audit live site
on:
  workflow_run:
    workflows: ["pages build and deployment"]
    types:
      - completed

jobs:

jobs:
  audit:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://blog.trnck.dev/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
